version: '3.8'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - admin_db

  admin_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - admin_db

  admin_db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_PASSWORD:
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306
